# Generated by Django 2.0.dev20170720150630 on 2017-08-23 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customerapp', '0001_initial'),
        ('driverapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('req_time', models.DateField()),
                ('picked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='driverapp.Driver')),
                ('raised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customerapp.Customer')),
            ],
        ),
    ]
