# Generated by Django 2.0.dev20170720150630 on 2017-08-23 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170823_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name_plural': 'Requests'},
        ),
    ]
