# Generated by Django 2.0.dev20170720150630 on 2017-08-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170823_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='complete_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='picked_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
